-- Active: 1733288777035@@127.0.0.1@5432@betafund
DROP TABLE IF EXISTS LETTER;
DROP TABLE IF EXISTS ANNUAL_REPORT;
DROP TABLE IF EXISTS DONOR;
DROP TABLE IF EXISTS EMPLOYER;
DROP TABLE IF EXISTS DONOR_CIRCLE;
DROP TABLE IF EXISTS CLASS_;
DROP TABLE IF EXISTS CLASS_COORDINATOR;
DROP TABLE IF EXISTS DONOR_ASSIGNMENT;
DROP TABLE IF EXISTS DONATION;
DROP TABLE IF EXISTS PHONOTHON;
DROP TABLE IF EXISTS DONATION;
DROP TABLE IF EXISTS EVENT_;
DROP TABLE IF EXISTS PAYMENT;